package br.projecao.ltpw.teste;
// Generated 06/05/2019 22:18:44 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Teste generated by hbm2java
 */
@Entity
@Table(name="teste"
    ,catalog="projecao"
)
public class Teste  implements java.io.Serializable {


     private int id;
     private String testeTb;

    public Teste() {
    }

	
    public Teste(int id) {
        this.id = id;
    }
    public Teste(int id, String testeTb) {
       this.id = id;
       this.testeTb = testeTb;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="teste_tb", length=30)
    public String getTesteTb() {
        return this.testeTb;
    }
    
    public void setTesteTb(String testeTb) {
        this.testeTb = testeTb;
    }




}


