package br.projecao.ltpw.model;
// Generated 06/05/2019 22:18:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Disciplina generated by hbm2java
 */
@Entity
@Table(name="Disciplina"
    ,catalog="projecao"
)
public class Disciplina  implements java.io.Serializable {


     private int idDisciplina;
     private Curso curso;
     private Set<Turma> turmas = new HashSet<Turma>(0);

    public Disciplina() {
    }

	
    public Disciplina(Curso curso) {
        this.curso = curso;
    }
    public Disciplina(Curso curso, Set<Turma> turmas) {
       this.curso = curso;
       this.turmas = turmas;
    }
   
     @Id @GeneratedValue

    
    @Column(name="idDisciplina", unique=true, nullable=false)
    public int getIdDisciplina() {
        return this.idDisciplina;
    }
    
    public void setIdDisciplina(int idDisciplina) {
        this.idDisciplina = idDisciplina;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCurso", nullable=false)
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="disciplina")
    public Set<Turma> getTurmas() {
        return this.turmas;
    }
    
    public void setTurmas(Set<Turma> turmas) {
        this.turmas = turmas;
    }




}


