package br.projecao.ltpw.model;
// Generated 06/05/2019 22:18:44 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Genero generated by hbm2java
 */
@Entity
@Table(name="Genero"
    ,catalog="projecao"
)
public class Genero  implements java.io.Serializable {


     private int idGenero;
     private String descricao;

    public Genero() {
    }

    public Genero(String descricao) {
       this.descricao = descricao;
    }
   
     @Id @GeneratedValue

    
    @Column(name="idGenero", unique=true, nullable=false)
    public int getIdGenero() {
        return this.idGenero;
    }
    
    public void setIdGenero(int idGenero) {
        this.idGenero = idGenero;
    }

    
    @Column(name="descricao", nullable=false, length=45)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


